import { useRouter } from "next/router";
import EditGame from "@/components/EditContent";
import Head from "next/head";
import Menu from "@/components/Menu";
import Container from "@/components/Container";
import Footer from "@/components/Footer";

export default function Edit() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>Editar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Menu />
        <Container>
          <EditGame id={id} />
        </Container>
      </main>
      <Footer/>


    </>
  );
}
